name: jenkins-8081
summary: Jenkins automation server
base: core18
description: |
  Jenkins is the leading open-source automation server. Built with Java, it
  provides over 1000 plugins to support automating virtually anything, so that
  humans can actually spend their time doing things machines cannot.
adopt-info: jenkins

confinement: classic
apps:
    jenkins:
        environment:
          SNAPCRAFT_BUILD_ENVIRONMENT: "host snapcraft --target-arch arm64"
          XDG_DATA_HOME: "$SNAP/usr/share"
          FONTCONFIG_PATH: "$SNAP/etc/fonts"
          JAVA_HOME: "$SNAP/usr/lib/jvm/java-11-openjdk"
          LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$LD_LIBRARY_PATH"
        command: |
            usr/lib/jvm/java-11-openjdk/bin/java -DJENKINS_HOME="$SNAP_DATA" -Djava.awt.headless=true -jar $SNAP/jenkins.war --httpPort=8091
        daemon: simple
    config:
        command: jenkins-config

parts:
    bsi-trigger: # A non-built part, only used to trigger builds in build.snapcraft.io on upstream changes
        plugin: nil
        source: https://github.com/jenkinsci/jenkins.git
    jenkins:
        plugin: nil
        stage-packages:
            - fonts-dejavu-core
            - libfontconfig1
            - openjdk-11-jre-headless
            - ca-certificates-java
        build-packages:
            - curl
            - unzip
            - libnss3
            - ca-certificates-java
        override-build: |
            curl -sLO http://mirrors.jenkins.io/war/latest/jenkins.war
            unzip jenkins.war META-INF/MANIFEST.MF
            VERSION=$(grep Jenkins-Version META-INF/MANIFEST.MF | cut -d' ' -f2 | tr -d '\r')
            rm META-INF/MANIFEST.MF
            mv $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-* $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk
            rm $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk/lib/security/cacerts
            cp /etc/ssl/certs/java/cacerts $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk/lib/security/cacerts
            cp /etc/ssl/certs/java/cacerts $SNAPCRAFT_PART_INSTALL/etc/ssl/certs/java/cacerts
            mv jenkins.war $SNAPCRAFT_PART_INSTALL
            snapcraftctl set-version "$VERSION"
    config:
        plugin: dump
        source: snap/local
        prime:
            - jenkins-config
